apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://meghanamaggie0987_db_user:OCqi0ccP4FY6fJKW@cluster0.dznw5it.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "secddfdfdret@2025"
  IMAGEKIT_PUBLIC_KEY : "public_4vVpHuamrKnZryZObxTA/q71H3Y="
  IMAGEKIT_PRIVATE_KEY : "private_fRlFvMDeS3cfnOpRPrV9I51iDFY="
  IMAGEKIT_URL_ENDPOINT : "https://ik.imagekit.io/2vf1onwk3"
  CLOUDINARY_API_SECRET : "RHJhZrqlNG9rzjjdfI4tjr2_c00"
  CLOUDINARY_API_KEY : "666956638599528"
  CLOUDINARY_CLOUD_NAME : "duwu4yrof"
  CLOUDINARY_URL : "cloudinary://666956638599528:RHJhZrqlNG9rzjjdfI4tjr2_c00@duwu4yrof"
  # Gemini API Key
  GEMINI_API_KEY : "AIzaSyAnhuxPbW0UOh7so8gFr_o1zTxUBMMw6Rk"